### ISSUE TITLE
A dialog with an id of 'hello:botkit-wrapper' wasn't found.

### ISSUE THREAD

**Issue by mdemin914** [howdyai/botkit-cms#21]
Hi, 

I am using botkit and have setup botkit-cms version 0.0.3 running locally. I added a new dialog named hello and saved it with the defaults. When I type hello into slack there is an error:

`A dialog with an id of 'hello:botkit-wrapper' wasn't found.`

I am using:
```
    "botbuilder-adapter-slack": "^1.0.2",
    "botkit": "^4.0.1",
    "botkit-plugin-cms": "^1.0.0"
```

I am not sure if its caused by the way botkit-cms writes the script file or if its the way the botkit/botworker reads the file. If I remove `id + ':botkit-wrapper'` from the botkit/botworker `beginDialog` code the hello dialog executes fine. 

Am I missing something simple?

Thanks!

**Comment by benbrown** [comment]
Apologies - there was a bug in 1.0 - updating to Botkit-plugin-cms 1.0.1 will solve this.

**Comment by mdemin914** [comment]
That was it thanks! I really like the cms!
