### ISSUE TITLE
Is a variation of doesn't seem to work

### ISSUE THREAD

**Issue by mdemin914** [howdyai/botkit-cms#22]
Hey,

I have a simple script configured to say yes or no based on the condition if `is variation of`
<img width="1576" alt="Screen Shot 2019-05-22 at 7 48 03 PM" src="https://user-images.githubusercontent.com/1123212/58222442-e93f7980-7cca-11e9-8856-6358af3b00e6.png">

However, it never seems to branch to the no condition.

<img width="386" alt="Screen Shot 2019-05-22 at 7 49 07 PM" src="https://user-images.githubusercontent.com/1123212/58222472-feb4a380-7cca-11e9-81fe-fcbadc0371d6.png">

I am using the following: 
```
 "botbuilder-adapter-slack": "^1.0.2",
"botbuilder-storage-mongodb": "^0.9.5",
"botkit": "^4.0.2",
"botkit-plugin-cms": "^1.0.1"
```
And botkit-cms version 0.0.3

Is there a config I am missing? Thanks!

**Comment by benbrown** [comment]
This functionality is not currently in Botkit 4.  However, the ability to recreate it will likely be included in an upcoming version.  Meanwhile, the regex pattern is still available --- and honestly, that's all that was happening behind the scenes anyways:

https://github.com/howdyai/botkit/blob/legacy/lib/utterances.json

**Comment by mdemin914** [comment]
Thanks!
