### ISSUE TITLE
Issue with Builder UI :: Quick Replies

### ISSUE THREAD

**Issue by gruntday** [howdyai/botkit-cms#7]
Hello,

having issues with building ui components .. i can not build quick replies using the interface

**Comment by gruntday** [comment]
![screenshot](https://user-images.githubusercontent.com/9366926/50548146-7c124580-0c50-11e9-92c6-204af0e5ada7.png)

@peterswimm as per screenshot i can not use quick replies .. platform Facebook .. no errors but the interface not showing quick replies as per the screenshot below 

![dialog](https://user-images.githubusercontent.com/9366926/50548167-b54ab580-0c50-11e9-913e-5850a06cece2.png)

**Comment by benbrown** [comment]
Do you have the PLATFORM variable set in your environment?

**Comment by gruntday** [comment]
@benbrown yes below is my .env

`# Chat platform
PLATFORM=[facebook]
`

**Comment by peterswimm** [comment]
@gruntday try removing the brackets

**Comment by benbrown** [comment]
@gruntday did you get this sorted out?

**Comment by peterswimm** [comment]
That's by design, You can only have one platform currently, and should not be using those brackets.
